apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: prometheus-stack
    env: dev
  name: prometheus
  namespace: observe
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: http-web 
    name: http-web 
  selector:
    app: prometheus-stack
    env: dev
  type: NodePort