apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: observe
  labels:
    type: local
    app: grafana
    env: dev
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/mnt/data"