apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
    env: dev
  name: grafana-datasources
  namespace: observe
stringData:
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus.observe.svc:9090",
                "version": 1
            }
        ]
    }
type: Opaque
