apiVersion: v1
kind: Secret
metadata:
  labels:
    app: grafana
    env: dev
  name: grafana-config
  namespace: observe
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC
type: Opaque
